-- 코드를 작성해주세요

SELECT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO I JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL


# SELECT CEIL(AVG(COALESCE(LENGTH, 10))) AS
# CASE WHEN THEN ELSE END AS
# DISTINCT(COUNT) AS
# FROM JOIN ON
# WHERE GROUP BY HAVING ORDER BY LIMIT