-- 코드를 입력하세요
SELECT ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE 
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE LIKE '%SUV%'


# SELECT ROUND(AVG(COALESCE(LENGTH,10)) 2) AS AVG
# CASE WHEN ELSE END AS CASE_NAME
# DISTINCT
# FROM 
# JOIN ON 
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT