-- 코드를 입력하세요
WITH GROUPY AS (
    SELECT CART_ID
        , GROUP_CONCAT(NAME) NAME
    FROM CART_PRODUCTS
    GROUP BY 1
)
SELECT CART_ID
FROM GROUPY
WHERE NAME RLIKE "Milk" AND NAME RLIKE "Yogurt"
ORDER BY 1