-- 코드를 작성해주세요
WITH PARENT AS(
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    )
, B_T AS (
SELECT P.ID AS A_ID
    , B.ID AS B_ID
FROM PARENT P
    LEFT JOIN ECOLI_DATA B ON P.ID = B.PARENT_ID
)
, C_T AS(
SELECT B.A_ID AS A_ID
    , B.B_ID AS B_ID
    , C.ID AS C_ID
FROM B_T B
    LEFT JOIN ECOLI_DATA C ON B.B_ID = C.PARENT_ID
)
SELECT C_ID AS ID
FROM C_T
WHERE C_ID IS NOT NULL
ORDER BY 1