-- 코드를 작성해주세요
WITH F AS( 
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
)
, S AS (
SELECT F.ID AS F_ID
    , S.ID AS S_ID
FROM F 
    LEFT JOIN ECOLI_DATA S ON F.ID = S.PARENT_ID
)
SELECT T.ID
FROM S
    LEFT JOIN ECOLI_DATA T ON S.S_ID = T.PARENT_ID
WHERE T.ID IS NOT NULL 
ORDER BY 1