-- 코드를 작성해주세요

WITH BASE AS (
    SELECT ID
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
)
, TWO AS (
SELECT ONE.ID
    , TWO.ID AS TWO_ID
FROM BASE ONE
    LEFT JOIN ECOLI_DATA TWO ON ONE.ID = TWO.PARENT_ID
)
SELECT THREE.ID AS ID
FROM TWO 
    LEFT JOIN ECOLI_DATA THREE ON TWO.TWO_ID = THREE.PARENT_ID
WHERE THREE.ID IS NOT NULL
ORDER BY 1