-- 코드를 입력하세요
SELECT COUNT(DISTINCT NAME) AS count
FROM ANIMAL_INS
WHERE NAME IS NOT NULL



# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS , COUNT(DISTINCT NAME) AS
# CASE WHEN ELSE THEN END AS
# DISTINCT
# FROM 
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT
