-- 코드를 작성해주세요
SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE (GENOTYPE & 2) = 0
AND ((GENOTYPE & 3) = 1 OR (GENOTYPE & 4) = 4)

# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS LENGTH
# CASE WHEN THEN ELSE END AS
# DISTINCT
# FROM 
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT 