SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE (GENOTYPE & 2) = 0
AND ((GENOTYPE & 1) = 1 OR (GENOTYPE & 4) = 4);

# SELECT COUNT IS NOT NULL 
# DISTINCT
# FROM 
# JOIN ON 
# WHERE
# GROUP BY 
# HAVING
# ORDER BY
# LIMIT