-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME 
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Dog' 
AND NAME LIKE '%el%'
ORDER BY NAME


# SELECT ROUND(AVG(COALESCE(LENGTH, 2)), 2) AS 
# CASE WHEN THEN ELSE END AS
# DISTINCT
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# DISTINCT