-- 코드를 작성해주세요
WITH PARENT_CNT AS(
SELECT PARENT_ID AS PARENT_ID
    , COUNT(*) AS CHILD_COUNT
FROM ECOLI_DATA
GROUP BY 1
)
SELECT A.ID
    , COALESCE(CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA A
    LEFT JOIN PARENT_CNT B ON A.ID = B.PARENT_ID
ORDER BY 1