-- 코드를 작성해주세요
SELECT SUM(PRICE) AS TOTAL_PRICE
FROM ITEM_INFO
WHERE RARITY LIKE "%LEGEND%"


# SELECT CEIL(AVG(COALESCE(LENGTH, 3)), 10) AS 
# DISTINCT(COUNT) AS
# CASE WHEN THEN ELSE END AS
# FROM JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT