-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')


# SELECT ROUND(AVG(COALESCE(LENGTH, 2)), 2) AS 
# CASE WHEN THEN ELSE END AS
# DISTINCT
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT