-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC


# SELECT FLOOR(AVG(COALESCE(LENGTH, 10)), 2) AS 
# CASE WHEN THEN ELSE END AS
# DISTINCT() AS
# FROM 
# JOIN ON 
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT