-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(S.SALES_AMOUNT * P.PRICE) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SUM(S.SALES_AMOUNT * P.PRICE) DESC, P.PRODUCT_CODE ASC


# SELECT CEIL(AVG(COALECSE(HELLO, 10)), 1) AS
# CASE WHEN THEN ELSE END AS
# DISTICNT(COUNT) AS 
# FROM 
# JOIN ON 
# WHERE 
# GROUP BY
# HAVING
# ORDER BY 
# LIMIT 