-- 코드를 입력하세요
SELECT P.PRODUCT_CODE 
    , SUM(O.SALES_AMOUNT * P.PRICE) AS SALES 
FROM OFFLINE_SALE O
    LEFT JOIN PRODUCT P ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY 1
ORDER BY SALES DESC, PRODUCT_CODE