-- 코드를 입력하세요
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE YEAR(JOINED) = 2021 AND AGE BETWEEN 20 AND 29



# SELECT ROUND(AVG(COALESCE, 10), 2) AS 
# CASE WHEN THEN ELSE END 
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY 
# LIMIT 