-- 코드를 입력하세요
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE BETWEEN 20 AND 29
AND YEAR(JOINED) = 2021


# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS
# CASE WHEN THEN ELSE END AS
# DISTINCT
# FROM 
# JOIN ON
# WHERE 
# GROUP BY 
# HAVING
# ORDER BY
# LIMIT 