-- 코드를 입력하세요
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE YEAR(JOINED) = 2021
AND AGE BETWEEN 20 AND 29


# SELECT ROUND(COALESCE(AVG, 10), 2)
# AS DISTINCT(COUNT) AS
# CASE WHEN THEN ELSE END AS
# FROM
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT