-- 코드를 입력하세요
WITH BASE AS(
    SELECT *
    FROM ONLINE_SALE 

    UNION ALL

    SELECT OFFLINE_SALE_ID
        , NULL AS USER_ID
        , PRODUCT_ID
        , SALES_AMOUNT
        , SALES_DATE
    FROM OFFLINE_SALE 
)
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
    , PRODUCT_ID
    , USER_ID
    , SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM BASE
WHERE SALES_DATE LIKE '2022-03%'
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3
