-- 코드를 작성해주세요
SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS AVERAGE_LENGTH
FROM FISH_INFO 

# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS AVERAGE_LENGTH, CASE WHEN ELSE END AS 
# DISTINCT
# FROM
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT
