-- 코드를 입력하세요
WITH FILTER AS ( -- 렌트 불가능한 차
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01'
)
SELECT C.CAR_ID
    , C.CAR_TYPE
    , ROUND(DAILY_FEE * 30 * ((100 - DISCOUNT_RATE)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND C.CAR_TYPE IN ('세단', 'SUV')
WHERE 1=1 
    AND CAR_ID NOT IN (SELECT CAR_ID FROM FILTER)
    AND DURATION_TYPE = '30일 이상'
    AND ROUND(DAILY_FEE * 30 * ((100 - DISCOUNT_RATE)/100)) >=  500000 
    AND ROUND(DAILY_FEE * 30 * ((100 - DISCOUNT_RATE)/100)) <  2000000 
ORDER BY 3 DESC, 2, 1 DESC
