-- 코드를 입력하세요
WITH AVAIL AS(
SELECT DISTINCT CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-11-30' 
    AND END_DATE >= '2022-11-01'
)
SELECT CAR_ID  
    , C.CAR_TYPE
    , ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE 
WHERE 1=1 
    AND C.CAR_ID NOT IN (SELECT * FROM AVAIL)
    AND C.CAR_TYPE IN ('세단', 'SUV')
    AND D.DURATION_TYPE = '30일 이상'
    AND ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01 * 30) >= 500000
    AND ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01 * 30) < 2000000
ORDER BY 3 DESC, 2, 1 DESC
    