-- 코드를 입력하세요
WITH BEST AS(
    SELECT FOOD_TYPE
        , MAX(FAVORITES) MAX_FAV
    FROM REST_INFO
    GROUP BY 1
)
SELECT BASE.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO BASE
    LEFT JOIN BEST ON BASE.FOOD_TYPE = BEST.FOOD_TYPE
WHERE FAVORITES = MAX_FAV
ORDER BY 1 DESC