-- 코드를 작성해주세요

WITH BASE AS (
SELECT ID
    , NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS QUANTILE
FROM ECOLI_DATA
)
SELECT ID
    , CASE WHEN QUANTILE = 1 THEN 'CRITICAL'
        WHEN QUANTILE = 2 THEN 'HIGH'
        WHEN QUANTILE = 3 THEN 'MEDIUM'
        WHEN QUANTILE = 4 THEN 'LOW'
      END AS COLONY_NAME
FROM BASE
ORDER BY ID
