-- 코드를 작성해주세요
WITH BASE AS (
    SELECT ID 
    , NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS Q
    FROM ECOLI_DATA
)
SELECT ID
    , CASE WHEN Q = 1 THEN 'CRITICAL' 
           WHEN Q = 2 THEN 'HIGH'
           WHEN Q = 3 THEN 'MEDIUM'
           WHEN Q = 4 THEN 'LOW'
      END AS COLONY_NAME
FROM BASE
ORDER BY 1