-- 코드를 작성해주세요
SELECT CONCAT(MAX(LENGTH), 'cm') AS MAX_LENGTH
FROM FISH_INFO

# SELECT ROUND(AVG(COALESCE, 10), 2) AS 
# CASE WHEN THEN ELSE END
# DISTINCT
# FROM
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT