-- 코드를 입력하세요
WITH INTACT AS (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE RLIKE 'Intact'
)
SELECT ANIMAL_ID
    , ANIMAL_TYPE
    , NAME
FROM ANIMAL_OUTS
WHERE SEX_UPON_OUTCOME NOT RLIKE 'Intact'
    AND ANIMAL_ID IN (SELECT ANIMAL_ID FROM INTACT)