-- 코드를 입력하세요
SELECT ANIMAL_TYPE, COALESCE(NAME, 'No name'), SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID 


# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS 
# COUNT(DISTINCT NAME) AS
# DISTINCT
# FROM JOIN ON
# WHERE 
# GROUP BY
# HAVING
# ORDER BY