-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR
    , MONTH(SALES_DATE) AS MONTH
    , GENDER
    , COUNT(DISTINCT I.USER_ID) AS USERS
FROM ONLINE_SALE S
    JOIN USER_INFO I ON S.USER_ID = I.USER_ID 
WHERE I.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3