-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID ASC


# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS
# CASE WHEN THEN ELSE END AS
# DISTINCT
# FROM
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT