-- 코드를 입력하세요
WITH MP AS(
SELECT MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT 
    )
SELECT PRODUCT_ID
    , PRODUCT_NAME
    , PRODUCT_CD
    , CATEGORY
    , PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX_PRICE FROM MP)

