-- 코드를 입력하세요
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE IS NULL


# SELECT ROUND(AVG(COALESCE(LENGTH, 10)),2) AS 
# CASE WHEN THEN ELSE END AS
# DISTINCT
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT