-- 코드를 입력하세요
SELECT WAREHOUSE_ID
    , WAREHOUSE_NAME
    , ADDRESS
    , COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE 1=1 
    -- AND ADDRESS RLIKE '경기도'
    AND ADDRESS LIKE '경기도%'
ORDER BY 1 
    