-- 코드를 입력하세요
WITH AVERAGE AS(
    SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT CAR_ID
    , ROUND(AVG(DIFF), 1)AS AVERAGE_DURATION
FROM AVERAGE
GROUP BY 1
    HAVING AVG(DIFF) >= 7
ORDER BY 2 DESC, CAR_ID DESC
;
