-- 코드를 입력하세요
SELECT ANIMAL_ID 
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID ASC


# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS 
# CASE WHEN THEN ELSE END AS 
# DISTINCT
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT