-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC


# SELECT ROUND(AVG(COALESCE(LENGTH, 1)), 1) AS 
# CASE WHEN THEN ELSE END AS
# DISTINCT
# FROM
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT