-- 코드를 입력하세요
WITH JOINED AS (
    SELECT 
        USER_ID 
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)
, MONTHLY AS ( 
SELECT YEAR(SALES_DATE) YEAR
    , MONTH(SALES_DATE) MONTH 
    , COUNT(DISTINCT USER_ID) AS PURCHASED_USERS 
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM JOINED)
GROUP BY 1, 2
) 
SELECT YEAR
    , MONTH 
    , PURCHASED_USERS
    , ROUND(PURCHASED_USERS/(SELECT COUNT(*) FROM JOINED), 1) AS PURCHASED_RATIO
FROM MONTHLY
