-- 코드를 입력하세요
WITH FILTER AS(
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)
SELECT CAR_ID
    , CASE 
    WHEN CAR_ID NOT IN (SELECT DISTINCT CAR_ID FROM FILTER) THEN '대여 가능'
    ELSE '대여중'END AS AVAILABILITY 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1, 2
ORDER BY CAR_ID DESC 