-- 코드를 입력하세요
WITH LATEST AS(
    SELECT CAR_ID
        , HISTORY_ID AS MAX_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
    GROUP BY 1
    
) 
SELECT CAR_ID
    , CASE WHEN CAR_ID IN (SELECT CAR_ID FROM LATEST) THEN '대여중'
        ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY 1, 2
ORDER BY 1 DESC

