-- 코드를 입력하세요
WITH TEMP AS(
    SELECT HOST_ID, ID
    FROM PLACES 
    GROUP BY HOST_ID 
    HAVING COUNT(*) >= 2
)
SELECT ID, NAME, HOST_ID
FROM PLACES 
WHERE HOST_ID IN (SELECT DISTINCT HOST_ID FROM TEMP)
ORDER BY 1
