-- 코드를 입력하세요
SELECT COUNT(*) AS count
FROM ANIMAL_INS

# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS 
# CASE WHEN THEN ELSE END
# DISTINCT
# FROM JOIN ON 
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT