-- 코드를 입력하세요
SELECT 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME, 
    SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;
# WITH FILTER AS(
#     SELECT PRODUCT_ID, PRODUCE_DATE
#     FROM FOOD_ORDER P 
#     WHERE YEAR(P.PRODUCE_DATE) = 2022
#         AND MONTH(P.PRODUCE_DATE) = 5
# )

# SELECT O.PRODUCT_ID
#     , PRODUCT_NAME
#     , SUM(AMOUNT * PRICE) AS TOTAL_SALES
# FROM FOOD_ORDER O
#     JOIN FOOD_PRODUCT P ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE O.PRODUCT_ID IN (SELECT PRODUCT_ID FROM FILTER)
# GROUP BY 1, 2
# ORDER BY 3 DESC, 1