-- 코드를 입력하세요
WITH BASE AS( 
SELECT HISTORY_ID
    , CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
     WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
     WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    END AS DURATION_TYPE
    , DATEDIFF(END_DATE, START_DATE) +1 AS DURATION
    , DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '트럭'
)
SELECT HISTORY_ID
    , ROUND(DAILY_FEE * DURATION * ( 100 - COALESCE(DISCOUNT_RATE, 0)) * 0.01) AS FEE
FROM BASE B
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON B.DURATION_TYPE = P.DURATION_TYPE 
                                                AND P.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC
