-- 코드를 입력하세요

WITH BASE AS(
SELECT HISTORY_ID
        , DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
        , DAILY_FEE
    , CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID 
WHERE C.CAR_TYPE = '트럭'
    )
SELECT HISTORY_ID
    # , B.DURATION_TYPE
    # , DISCOUNT_RATE
    , ROUND(DURATION * (100 - COALESCE(DISCOUNT_RATE, 0)) * 0.01 * DAILY_FEE) AS FEE
FROM BASE B
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON D.DURATION_TYPE = B.DURATION_TYPE AND D.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC
