-- 코드를 입력하세요
WITH BASE AS(
SELECT HISTORY_ID
    , CAR_ID
    , START_DATE
    , END_DATE
    , DATEDIFF(END_DATE, START_DATE) +1 AS DURATION
    , CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1  >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1  >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1  >= 7 THEN '7일 이상'
    END AS DURATION_TYPE 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
)
SELECT HISTORY_ID
    , ROUND(DURATION * DAILY_FEE * ((100 - IFNULL(DISCOUNT_RATE, 0))/100)) AS FEE
FROM BASE
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON BASE.DURATION_TYPE = D.DURATION_TYPE AND D.CAR_TYPE = '트럭'
    JOIN CAR_RENTAL_COMPANY_CAR C ON BASE.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC
