-- 코드를 입력하세요
WITH RECURSIVE H AS(
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 
    FROM H
    WHERE HOUR < 23
)
SELECT HOUR 
    , COUNT(ANIMAL_ID) AS COUNT
FROM H
    LEFT JOIN ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY 1
ORDER BY 1


