-- 코드를 작성해주세요
WITH CODES AS(

SELECT CODE 
FROM SKILLCODES 
    WHERE CATEGORY = 'Front End'

)
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
JOIN CODES C ON D.SKILL_CODE & C.CODE > 0
ORDER BY 1
