-- 코드를 작성해주세요
WITH FILTER AS( 
SELECT *
FROM SKILLCODES
WHERE CATEGORY = 'Front End'
)
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
    JOIN FILTER F ON (D.SKILL_CODE & F.CODE) > 0 
ORDER BY ID 