-- 코드를 입력하세요
SELECT PT_NAME, PT_NO, GEND_CD, AGE, COALESCE(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC


# SELECT ROUND(AVG(COALESCE(LENGTH,10)), 1) AS 
# CASE WHEN THEN ELSE END AS 
# DISTINCT
# FROM 
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT