-- 코드를 입력하세요
WITH SALES AS(
    SELECT WRITER_ID
        , SUM(PRICE) PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY 1
    HAVING SUM(PRICE) >= 700000
)
SELECT U.USER_ID
    , U.NICKNAME
    , S.PRICE
FROM SALES S
    LEFT JOIN USED_GOODS_USER U ON U.USER_ID = S.WRITER_ID
ORDER BY 3 