-- 코드를 작성해주세요
WITH YEAR_SCORE AS(
    SELECT EMP_NO  
        , CASE WHEN AVG(SCORE) >= 96 THEN 'S'
            WHEN AVG(SCORE) >= 90 THEN 'A'
            WHEN AVG(SCORE) >= 80 THEN 'B'
            ELSE 'C'
         END AS GRADE
        , CASE WHEN AVG(SCORE) >= 96 THEN 0.2
            WHEN AVG(SCORE) >= 90 THEN 0.15
            WHEN AVG(SCORE) >= 80 THEN 0.1
            ELSE 0
         END AS GRADE_RATIO
    FROM HR_GRADE
    GROUP BY 1
    )
SELECT YS.EMP_NO
    , EMP_NAME
    , GRADE
    , SAL * GRADE_RATIO AS BONUS
FROM YEAR_SCORE YS
    LEFT JOIN HR_EMPLOYEES E ON E.EMP_NO = YS.EMP_NO
ORDER BY 1 
