-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR BETWEEN 9 AND 20
ORDER BY HOUR

# SELECT ROUND(COALESCE(AVG, 10), 2) AS DISTINCT(COUNT) AS 
# CASE WHEN THEN ELSE END AS
# FROM 
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# DISTINCT