-- 코드를 작성해주세요
SELECT I.ITEM_ID
    , I.ITEM_NAME
    , I.RARITY
FROM ITEM_INFO I
    JOIN ITEM_TREE T ON T.ITEM_ID = I.ITEM_ID
WHERE PARENT_ITEM_ID IS NOT NULL
AND PARENT_ITEM_ID IN (SELECT ITEM_ID 
                       FROM ITEM_INFO 
                       WHERE RARITY = 'RARE')
ORDER BY 1 DESC
;
# SELECT I.ITEM_ID
#      , I.ITEM_NAME
#      , I.RARITY
# FROM ITEM_INFO I
# JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
# WHERE T.PARENT_ITEM_ID IN (
#     -- 부모 아이템의 희귀도가 'RARE'인 아이템 ID들만 추출
#     SELECT ITEM_ID 
#     FROM ITEM_INFO 
#     WHERE RARITY = 'RARE'
# )
# ORDER BY I.ITEM_ID DESC;