-- 코드를 작성해주세요

WITH TEMP AS(
    SELECT ITEM_ID 
    FROM ITEM_INFO 
    WHERE RARITY = 'RARE'
)
SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE T
LEFT JOIN ITEM_INFO I ON I.ITEM_ID = T.ITEM_ID 
WHERE 1=1 
    AND PARENT_ITEM_ID IS NOT NULL
    AND T.PARENT_ITEM_ID IN (SELECT DISTINCT ITEM_ID FROM TEMP)
ORDER BY ITEM_ID DESC