-- 코드를 입력하세요
SELECT FLAVOR 
FROM FIRST_HALF 
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC


# SELECT ROUND(AVG(COALECE(LENGTH, 10)), 2) AS
# CASE WHEN THEN ELSE END AS 
# DISTINCT
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT 