-- 코드를 작성해주세요

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS 
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "Python") OR
SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID ASC



# SELECT CEIL(AVG(COALESCE(LENGTH, 10))) AS
# CASE WHEN THEN ELSE END AS
# DISTINCT(COUNT) AS
# FROM JOIN ON
# WHERE (SELECT FROM WHERE)
# GROUP BY HAVING
# ORDER BY
# LIMIT