-- 코드를 작성해주세요
WITH FILTER AS( 
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
    )
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
    JOIN FILTER F ON (D.SKILL_CODE & F.CODE) > 0
ORDER BY 1