-- 코드를 작성해주세요
WITH FILTERS AS(
    SELECT *
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
    JOIN FILTERS S ON (S.CODE & D.SKILL_CODE) > 0
ORDER BY 1  
