-- 코드를 입력하세요
SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY,
       COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;


# SELECT ROUND(AVG(COALESCE, 10), 10) AS 
# DISTINCT(COUNT) AS 
# CASE WHEN THEN ELSE END AS
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT