-- 코드를 작성해주세요
WITH BEST AS(
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) AS LARGEST
    FROM ECOLI_DATA
    GROUP BY 1
)
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
    , LARGEST - SIZE_OF_COLONY AS YEAR_DEV
    , ID
FROM ECOLI_DATA BASE
LEFT JOIN BEST B ON B.YEAR = YEAR(BASE.DIFFERENTIATION_DATE)
ORDER BY 1, 2 