-- 코드를 작성해주세요
WITH LARGEST AS(
    SELECT  FISH_TYPE
        , MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY 1
)
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_NAME_INFO N
    LEFT JOIN FISH_INFO I ON I.FISH_TYPE = N.FISH_TYPE 
    JOIN LARGEST L ON L.FISH_TYPE = N.FISH_TYPE AND L.MAX_LENGTH = I.LENGTH
ORDER BY 1 

    