-- 코드를 입력하세요
SELECT BOOK_ID, 
DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK 
WHERE YEAR(PUBLISHED_DATE) = 2021 
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC


# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS QUE
# DISTINCT
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT