-- 코드를 작성해주세요

WITH TEMP AS(
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE 
    WHERE YEAR = 2022
    GROUP BY 1
    ORDER BY 2 DESC
    LIMIT 1
)
SELECT SCORE, T.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM TEMP T 
    LEFT JOIN HR_EMPLOYEES E ON T.EMP_NO = E.EMP_NO
