-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# B.BOARD_ID, B.WRITER_ID, B.TITLE, B.CONTENTS, B.PRICE, B.CREATED_DATE, B.STATUS, B.VIEWS
# R.REPLY_ID, R.BORAD_ID, R.WRITER_ID, R.CONTENTS, R.CREATED_DATE
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC



# SELECT COUNT() AS COUNT
# DISTINCT
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT