-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, 
DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC

# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS 
# CASE WHEN THEN ELSE END
# DISTINCT
# FROM 
# JOIN ON 
# GROUP BY 
# HAVING
# ORDER BY 
# LIMIT