-- 코드를 입력하세요
SELECT * FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY CAR_ID DESC


# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS 
# CASE WHEN THEN ELSE END AS
# DISTINCT
# FROM JOIN ON 
# WHERE
# GROUP BY 
# HAVING
# ORDER BY
# LIMIT 
