-- 코드를 입력하세요
WITH MAX_PRICE AS(
    SELECT CATEGORY 
        , MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY 1
    )
SELECT P.CATEGORY
    , MAX_PRICE
    , PRODUCT_NAME
FROM FOOD_PRODUCT P 
    JOIN MAX_PRICE M ON P.PRICE = M.MAX_PRICE AND P.CATEGORY = M.CATEGORY
ORDER BY MAX_PRICE DESC