-- 코드를 작성해주세요

WITH MORE_AVG AS (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(COALESCE(LENGTH, 10)) >= 33
    )

SELECT COUNT(*) AS FISH_COUNT 
    , MAX(LENGTH) AS MAX_LENGTH
    , FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT * FROM MORE_AVG)
GROUP BY 3
ORDER BY 3