-- 코드를 작성해주세요
WITH BASE AS(
SELECT ID
    , EMAIL
    , GROUP_CONCAT(NAME) NAME 
    , GROUP_CONCAT(DISTINCT CATEGORY) CATEGORY 
FROM DEVELOPERS D
    LEFT JOIN SKILLCODES S ON (S.CODE & D.SKILL_CODE) > 0 
GROUP BY 1, 2
),
FINAL AS(
SELECT CASE WHEN CATEGORY RLIKE 'Front End' AND NAME RLIKE 'Python' THEN 'A'
            WHEN NAME RLIKE 'C#' THEN 'B'
            WHEN CATEGORY RLIKE 'Front End' THEN 'C'
        END AS GRADE
    , ID, EMAIL
FROM BASE B
)
SELECT * FROM FINAL WHERE GRADE IS NOT NULL ORDER BY 1, 2
