-- 코드를 작성해주세요

WITH BASE AS(
SELECT ID
    , EMAIL
    , MAX(CASE WHEN CATEGORY = 'Front End' THEN 1 ELSE 0 END) AS FE
    , MAX(CASE WHEN NAME = 'Python' THEN 1 ELSE 0 END ) AS PY
    , MAX(CASE WHEN NAME = 'C#' THEN 1 ELSE 0 END) AS CC
FROM DEVELOPERS D
    LEFT JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE > 0
GROUP BY 1, 2
)
, GRADING AS (
SELECT CASE WHEN FE = 1 AND PY = 1 THEN 'A'
        WHEN CC = 1 THEN 'B'
        WHEN FE = 1 THEN 'C'
        END AS GRADE
        , ID
        , EMAIL
FROM BASE
    )
SELECT * 
FROM GRADING 
WHERE GRADE IS NOT NULL 
ORDER BY 1 , 2

