-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE CATEGORY LIKE '%경제%'
ORDER BY PUBLISHED_DATE ASC


# SELECT CEIL(AVG(COALESCE(LENGTH, 10)), 2) AS 
# DISTINCT(COUNT) AS
# CASE WHEN THEN ELSE END AS
# FROM
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY 
# LIMIT