-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME,'%Y-%m-%d') AS 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

# SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS 
# DISTINCT(COUNT) AS 
# CASE WHEN THEN ELSE END AS
# FROM 
# JOIN ON
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT