-- 코드를 입력하세요
SELECT FLOOR(PRICE/10000) * 10000 AS PRICE_GROUP, 
COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY FLOOR(PRICE/10000)
ORDER BY PRICE_GROUP ASC;


# SELECT LEFT(WORD, 2) AS DISTINCT(COUNT) AS 
# ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS 
# CASE WHEN ELSE THEN END (AS)
# FROM 
# WHERE
# GROUP BY
# HAVING
# ORDER BY
# LIMIT 